CREATE OR REPLACE TABLE feedback_stg_tmp(
    username VARCHAR,
    email VARCHAR,
    user_id VARCHAR,
    age NUMBER,  
    feedback VARCHAR,
    input_url VARCHAR,
    recommendation_rank NUMBER,
    would_recommend_to_friend_rank NUMBER,
    purchased INTEGER, 
    added_to_wantlist INTEGER,
    familiarity VARCHAR,
    shared_with_friends INTEGER,
    recommendation_relevance VARCHAR,
    interaction_timestamp TIMESTAMP, 
    country VARCHAR,
    city VARCHAR,
    device_type VARCHAR,
    device_os VARCHAR,
    device_browser VARCHAR,
    session_id VARCHAR,
    session_duration NUMBER,
    n_clicks NUMBER,
    n_recs_purchased NUMBER,
    n_recs_added_in_wantlist NUMBER
);
