location_data = [
    {"country": "Germany", "city": "Berlin"},
    {"country": "France", "city": "Paris"},
    {"country": "Spain", "city": "Barcelona"},
    {"country": "Spain", "city": "Madrid"},
    {"country": "Ukraine", "city": "Kyiv"},
    {"country": "Ukraine", "city": "Odessa"},
    {"country": "Italy", "city": "Rome"},
    {"country": "Netherlands", "city": "Amsterdam"},
    {"country": "Sweden", "city": "Stockholm"},
    {"country": "Denmark", "city": "Copenhagen"},
    {"country": "Austria", "city": "Vienna"},
    {"country": "Belgium", "city": "Brussels"},
    {"country": "Belgium", "city": "Antwerp"},
    {"country": "Poland", "city": "Warsaw"},
    {"country": "Greece", "city": "Athens"},
    {"country": "Portugal", "city": "Lisbon"},
    {"country": "Czech Republic", "city": "Prague"},
    {"country": "Ireland", "city": "Dublin"},
    {"country": "Finland", "city": "Helsinki"},
    {"country": "United States", "city": "New York"},
    {"country": "United States", "city": "Los Angeles"},
    {"country": "United States", "city": "Chicago"},
    {"country": "United States", "city": "San Francisco"},
    {"country": "United States", "city": "Detroit"},
    {"country": "United States", "city": "Miami"},
    {"country": "Switzerland", "city": "Zurich"},
    {"country": "Norway", "city": "Oslo"},
    {"country": "Turkey", "city": "Istanbul"},
    {"country": "Japan", "city": "Tokyo"},
    {"country": "South Korea", "city": "Seoul"},
]
